
# language: haskell
# before_install:
#     - "cabal update"
#     - "cabal install hspec"
#     - "cabal install happy"



# See http://www.reddit.com/r/haskell/comments/1os3f6/how_to_use_travisci_with_multiple_ghc_versions/

env:
 # - GHCVER=6.12.3
 # - GHCVER=7.0.1
 # - GHCVER=7.0.2
 # - GHCVER=7.0.3
 # - GHCVER=7.0.4
 # - GHCVER=7.2.1
 # - GHCVER=7.2.2
# - GHCVER=7.4.1
 - GHCVER=7.4.2
# - GHCVER=7.6.1
# - GHCVER=7.6.2
 - GHCVER=7.6.3
 - GHCVER=7.8.2
# - GHCVER=head

matrix:
  allow_failures:
   - env: GHCVER=7.8.2

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install cabal-install-1.18 ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH

install:
 - cabal-1.18 update
 # - cabal-1.18 install QuickCheck-2.6 # hspec is broken against 2.7
 - cabal-1.18 install happy
 - cabal-1.18 install alex
 # - cabal-1.18 install haddock
 # - cabal-1.18 install haddock-2.13.2.1
 # - cabal-1.18 install haddock-2.11.1
 # - cabal-1.18 install hspec-discover # For one of the tests
 - if [ "$GHCVER" = "6.12.3" ]; then
      cabal-1.18 install --only-dependencies;
      cabal-1.18 install 'QuickCheck==2.6.*';
   else
      cabal-1.18 install --only-dependencies --enable-tests;
   fi

script:
 # - cd tests/ && runghc ./GenTests.hs && cd ..
 - cabal-1.18 configure --enable-tests
 - cabal-1.18 build
 - cabal-1.18 test
 - cabal-1.18 check
 - if [ "$GHCVER" = "7.4.2" ]; then
      echo "skipping";
   else
      cabal-1.18 haddock;
   fi
 - cabal-1.18 sdist

notifications:
  irc: "irc.freenode.org#haskell-refactorer"

